version: "2.1"
services:
  wake-on-lan:
    restart: always
    image: ghcr.io/bucknalla/wol-block:latest
    network_mode: host
    ports:
      - "80:80"
      - "9:9"
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
    environment:
      - "DEBUG=main,endpoints"
      - "PORT=3000"
